### ISSUE TITLE
[2] Reports design CSS quirks fix

### ISSUE THREAD

**Issue by caioertai** [mwalsh2020/lsat-cracked#136]
- [x] Move status tags to the left.
- [x] Uncapitalize question titles

**Comment by jamiesonreinhard** [comment]
Status tags are aligned to the left now. 

I'm having trouble with uncapitalize. The ruby downcase method doesn't work on this (is this because of the method "to_plain_text"?). 

I can use CSS to either lowercase everything or capitalize every word or the first word of the first sentence. I'm not sure how to capitalize the first word of EACH sentence. @caioertai any hints?

**Comment by caioertai** [comment]
Let me have a look, @jamiesonreinhard . I don't think the titles themselves are capitalized in the DB. So it's more like stopping it from being capitalized in the page. In general I think it's better if you open a PR for those checks, so I can look at the code progress.

**Comment by jamiesonreinhard** [comment]
Right, that's what I was thinking too about stopping it from being capitalized @caioertai, just haven't figured out how yet. I'll create a pull request.
